<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="OB-Sum" failures="1" tests="1" name="Ledger_Reconciliation" time="60.577" errors="0" timestamp="2021-11-11T12:57:06 IST">
  <testcase classname="test.ashiv.TestLadgerRecon_DefaultProfile" name="GoToUrlClickView2ClickLedgerReconciliation3PositiveSelectAccountType48PositiveSelectAccount59C" time="58.355">
    <failure type="java.lang.AssertionError" message="Unable to locate object: By.xpath: //*[@id=&amp;apos;ctl00_cPH_rptrAccount_ctl01_rptrReconcile_ctl00_lnkUngroup&amp;apos;]">
      <![CDATA[java.lang.AssertionError: Unable to locate object: By.xpath: //*[@id='ctl00_cPH_rptrAccount_ctl01_rptrReconcile_ctl00_lnkUngroup']
at org.testng.Assert.fail(Assert.java:99)
at As_Supplier.Ledger_Reconciliation2.Click_Undo_Reconcile_13(Ledger_Reconciliation2.java:359)
at test.ashiv.TestLadgerRecon_DefaultProfile.GoToUrlClickView2ClickLedgerReconciliation3PositiveSelectAccountType48PositiveSelectAccount59C(TestLadgerRecon_DefaultProfile.java:156)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GoToUrlClickView2ClickLedgerReconciliation3PositiveSelectAccountType48PositiveSelectAccount59C -->
</testsuite> <!-- Ledger_Reconciliation -->
