<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OB-Sum" failures="3" tests="3" name="Ashiv_tests_Demo.Testlogin2_DefaultProfile" time="25.865" errors="0" timestamp="2021-09-17T14:23:39 IST" skipped="0">
  <testcase classname="Ashiv_tests_Demo.Testlogin2_DefaultProfile" name="GoToUrlAssertUrlPositiveEnterEmailOrNameNegativeEnterPasswordError" time="9.009">
    <failure message="Expecting URL - https://ashiv.cloud.testinsights.io/app/#!/test-modeller/100021 Found http://sandbox4.nomismasolution.co.uk/ssoui/Signin.aspx?token=668f28ac-236f-4d7a-9aa3-2a9457140633" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expecting URL - https://ashiv.cloud.testinsights.io/app/#!/test-modeller/100021 Found http://sandbox4.nomismasolution.co.uk/ssoui/Signin.aspx?token=668f28ac-236f-4d7a-9aa3-2a9457140633
at org.testng.Assert.fail(Assert.java:99)
at Ashiv_Demo_Pages.TestModellerio_Quality_with_Every_Release.AssertUrl(TestModellerio_Quality_with_Every_Release.java:60)
at Ashiv_tests_Demo.Testlogin2_DefaultProfile.GoToUrlAssertUrlPositiveEnterEmailOrNameNegativeEnterPasswordError(Testlogin2_DefaultProfile.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GoToUrlAssertUrlPositiveEnterEmailOrNameNegativeEnterPasswordError -->
  <system-out/>
  <testcase classname="Ashiv_tests_Demo.Testlogin2_DefaultProfile" name="GoToUrlAssertUrlNegativeEnterEmailOrNameError" time="8.714">
    <failure message="Expecting URL - https://ashiv.cloud.testinsights.io/app/#!/test-modeller/100021 Found http://sandbox4.nomismasolution.co.uk/ssoui/Signin.aspx?token=668f28ac-236f-4d7a-9aa3-2a9457140633" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expecting URL - https://ashiv.cloud.testinsights.io/app/#!/test-modeller/100021 Found http://sandbox4.nomismasolution.co.uk/ssoui/Signin.aspx?token=668f28ac-236f-4d7a-9aa3-2a9457140633
at org.testng.Assert.fail(Assert.java:99)
at Ashiv_Demo_Pages.TestModellerio_Quality_with_Every_Release.AssertUrl(TestModellerio_Quality_with_Every_Release.java:60)
at Ashiv_tests_Demo.Testlogin2_DefaultProfile.GoToUrlAssertUrlNegativeEnterEmailOrNameError(Testlogin2_DefaultProfile.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GoToUrlAssertUrlNegativeEnterEmailOrNameError -->
  <system-out/>
  <testcase classname="Ashiv_tests_Demo.Testlogin2_DefaultProfile" name="GoToUrlAssertUrlPositiveEnterEmailOrNamePositiveEnterPasswordLogin" time="8.142">
    <failure message="Expecting URL - https://ashiv.cloud.testinsights.io/app/#!/test-modeller/100021 Found http://sandbox4.nomismasolution.co.uk/ssoui/Signin.aspx?token=668f28ac-236f-4d7a-9aa3-2a9457140633" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expecting URL - https://ashiv.cloud.testinsights.io/app/#!/test-modeller/100021 Found http://sandbox4.nomismasolution.co.uk/ssoui/Signin.aspx?token=668f28ac-236f-4d7a-9aa3-2a9457140633
at org.testng.Assert.fail(Assert.java:99)
at Ashiv_Demo_Pages.TestModellerio_Quality_with_Every_Release.AssertUrl(TestModellerio_Quality_with_Every_Release.java:60)
at Ashiv_tests_Demo.Testlogin2_DefaultProfile.GoToUrlAssertUrlPositiveEnterEmailOrNamePositiveEnterPasswordLogin(Testlogin2_DefaultProfile.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GoToUrlAssertUrlPositiveEnterEmailOrNamePositiveEnterPasswordLogin -->
  <system-out/>
</testsuite> <!-- Ashiv_tests_Demo.Testlogin2_DefaultProfile -->
